In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [6]:
csvs = os.listdir()

for csv in csvs:
  if csv[:-3] == 'csv':
    pd.read_csv(csv)

In [12]:
df = pd.read_csv(r'D:\U\Proyecto ruido y vibraciones\csv\crv1.csv',sep=';', decimal=',')

df

,Tiempo,67Hz,71Hz,75Hz,79Hz,84Hz,89Hz,94Hz,100Hz,106Hz,...,"4,47kHz","4,73kHz","5,01kHz","5,31kHz","5,62kHz","5,96kHz","6,31kHz","6,68kHz","7,08kHz","7,5kHz"
0,01-01-2000 0:07,22.98,24.47,25.51,20.39,28.19,28.73,28.09,29.67,27.58,...,18.10,17.52,13.60,15.69,17.34,18.37,20.40,15.95,13.34,13.78
1,01-01-2000 0:07,22.53,31.85,28.47,12.60,23.38,29.31,33.01,39.61,24.69,...,18.84,17.54,12.62,13.70,17.45,19.04,20.70,16.08,13.78,14.67
2,01-01-2000 0:07,17.18,26.56,19.29,14.68,27.50,23.00,26.02,32.12,30.08,...,18.58,16.20,13.75,15.23,15.87,18.44,19.44,15.83,13.02,14.30
3,01-01-2000 0:07,26.53,28.84,29.98,22.54,28.66,33.12,36.92,37.38,29.79,...,19.35,17.44,15.70,17.70,17.12,19.00,20.08,16.54,14.79,16.02
4,01-01-2000 0:07,16.46,35.48,32.25,16.36,23.10,30.90,30.56,35.18,31.82,...,16.34,15.92,14.80,15.48,16.66,18.23,19.21,15.92,14.24,14.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559,01-01-2000 0:12,26.17,26.80,28.22,18.87,22.49,21.01,35.36,37.36,30.80,...,22.30,19.77,21.08,22.61,18.05,20.08,20.43,17.81,17.22,16.36
560,01-01-2000 0:12,28.32,36.68,34.91,15.99,20.29,28.96,33.89,31.09,24.82,...,18.84,13.20,14.16,20.44,13.86,15.50,17.74,15.52,13.02,12.98
561,01-01-2000 0:12,23.52,28.02,31.53,13.26,20.39,26.40,22.74,31.06,24.60,...,19.50,13.70,14.45,20.13,14.54,14.81,19.18,15.17,13.70,13.06
562,01-01-2000 0:12,16.78,30.49,27.06,15.58,24.51,22.43,32.98,30.67,28.08,...,19.33,13.84,14.22,19.58,14.48,14.58,19.73,15.76,13.07,12.97
563,01-01-2000 0:12,25.74,23.51,30.84,22.07,32.97,31.39,31.73,38.03,33.46,...,19.95,18.92,16.84,19.09,20.07,20.30,22.53,17.78,23.61,20.02

In [17]:
df = df.apply(lambda x: 10**(x/10))

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [15]:
n = len(df)
niveles = []
for freq in df:
  niveles.append(10*np.log10((1/n)*np.sum(df[freq])))

TypeError: can't multiply sequence by non-int of type 'float'

In [ ]:
niveles

[2.1141260713035854, 3.114126071303585, 4.114126071303585]

In [ ]:
df.to_csv('niveles.csv')